### ISSUE TITLE
utils/scan with colmap option

### ISSUE THREAD

**Issue by KevinCain** [raphaelsulzer/dgnn#2]
I see the provided `/utils/scan` binary supports colmap sources as shown below. This suggests the binary may take as input the set of colmap sparse reconstruction outputs `cameras.bin`, `images.bin`, and `points3D.bin`.

Is this correct, and could you suggest a sample invocation?

On a connected point, if we begin with a point cloud, can you confirm that we need to provide a starting mesh to `utils/scan` via `-i mesh.off`? That is, `/utils/scan` reports that it requires 1) an _input_ mesh (as .off), which is a bit confusing since the the utility _outputs_ 2) a Delaunay triangulation via virtual scanning as a prerequisite to the 3) final dgnn mesh.

```
-s [ --source ] arg (=ply)        Data source and options:
-ply
-npz
-colmap
-omvs
-scan,#points,#cameras,std_noise,%outliers
-tt,#scans
-eth
```

**Comment by raphaelsulzer** [comment]
Hi,
thank you for your interest in the work.

For clarification, you only need the `scan` utility if you have ground truth meshes, which you want to sample using virtual scanning. So either you have a dataset with ground truth meshes and you want to train DGNN on it, or you want to evaluate the performance of DGNN reconstructions.

If you simply want to reconstruct a mesh starting from a point cloud, you do not need the `scan` utility. In this case you start with your point cloud with visibility information (e.g. in .npz file format) and extract features for DGNN like this:

```
utils/feat -w /pathToWorkingdir/ -i yourPointcloudFile -s npz
```

Then you make a custom.yaml file which points to /pathToWorkingdir/ and you can reconstruct a mesh from your point cloud.

### COLMAP
`feat` used to be able to input a COLMAP point cloud in the way you suggest. It stopped working at some point due to some [issues with Eigen versions which I could never fix](https://github.com/colmap/colmap/issues/820).

The easiest way to get this done is to use the [OpenMVS InterfaceCOLMAP tool](https://github.com/cdcseacave/openMVS/tree/master/apps/InterfaceCOLMAP) to create an OpenMVS project from a COLMAP project. Then you can run:


```
utils/feat -w /pathToWorkingdir/ -i yourOpenMvsProjectFile -s omvs
```

If you have problems with this part, or you really want to get the COLMAP thing to work I suggest you have a look at the code in [mesh-tools](https://github.com/raphaelsulzer/mesh-tools) and open an issue there if necessary.

Hope this helps!

**Comment by KevinCain** [comment]
Thank you @raphaelsulzer for these helpful notes.

I has no trouble refreshing my OpenMVS repo and exporting pinhole cameras from a test scene, but I must not be correctly setting the scene for the `dgnn` helper `feat`.

I successfully exported an OpenMVS file from a undistorted colmap scene (images, database, the usual binary sparse reconstruction files) with:
```
cd ~/openMVS_build/bin
./InterfaceCOLMAP --archive-type -1 -i ~/undist/ -o Peterson.omvs
```
Next I invoked features in `dgnn` from the dgnn conda shell via:
```
utils/feat -w ~/undist/ -i Peterson.omvs -s omvs
```
This yields the following error:
```
-----FEATURE EXTRACTION-----

Working dir set to:
-/home/undist/
ERROR: not a valid reconstruction input
```
Am I ignoring other context we must supply to `dgnn`?

In case it's relevant, the output of my conversion from colmap to OpenMVS follows. It looks OK to me:
```
./InterfaceCOLMAP --archive-type -1 -i /home/kevin/Hierarchical-Localization/outputs/sfm/sfm_superpoint+superglue/undist/ -o Peterson
21:23:22 [App     ] Build date: Feb 21 2022, 19:43:43
21:23:22 [App     ] CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 cores)
21:23:22 [App     ] RAM: 15.58GB Physical Memory 32.72GB Virtual Memory
21:23:22 [App     ] OS: Linux 5.16.10-zen1-1-zen (x86_64)
21:23:22 [App     ] Disk: 131.38GB (448.36GB) space
21:23:22 [App     ] SSE & AVX compatible CPU & OS detected
21:23:22 [App     ] Command line: InterfaceCOLMAP --archive-type -1 -i /home/kevin/Hierarchical-Localization/outputs/sfm/sfm_superpoint+superglue/undist/ -oPeterson
21:23:22 [App     ] Reading cameras: /home/kevin/Hierarchical-Localization/outputs/sfm/sfm_superpoint+superglue/undist/sparse/cameras.bin
21:23:22 [App     ] Reading images: /home/kevin/Hierarchical-Localization/outputs/sfm/sfm_superpoint+superglue/undist/sparse/images.bin
21:23:22 [App     ] Reading points: /home/kevin/Hierarchical-Localization/outputs/sfm/sfm_superpoint+superglue/undist/sparse/points3D.bin
21:23:22 [App     ] Reading patch-match configuration: /home/kevin/Hierarchical-Localization/outputs/sfm/sfm_superpoint+superglue/undist/stereo/patch-match.cfg
21:23:22 [App     ] Reading depth-maps/normal-maps: /home/kevin/Hierarchical-Localization/outputs/sfm/sfm_superpoint+superglue/undist/stereo/depth_maps/ and/home/kevin/Hierarchical-Localization/outputs/sfm/sfm_superpoint+superglue/undist/stereo/normal_maps/
21:23:22 [App     ] Exported data: 60 images & 10724 vertices (26ms)
21:23:22 [App     ] MEMORYINFO: {
21:23:22 [App     ]     VmPeak:   517484 kB
21:23:22 [App     ]     VmSize:   516780 kB
21:23:22 [App     ] } ENDINFO
```

**Comment by raphaelsulzer** [comment]
If you use an omvs file as source, `feat` automatically appends `openMVS` to your working dir path. Sorry, this is a bit confusing, I should change this!

Can you put `Peterson.omvs` in a folder called `openMVS` and try again. 
So your structure should look like `~/undist/openMVS/Peterson.omvs`, but you still need to invoke `feat`with
`utils/feat -w ~/undist/ -i Peterson.omvs -s omvs`
Also it might then be necessary to move your undist images folder, so your OpenMVS project file points to the correct path after you have moved it. But I'm not sure about this last thing, and I can't test it right now.

Hope it works. I'll upload a new `feat` executable soon for easier use.

**Comment by raphaelsulzer** [comment]
Hi,

I'm sorry but I forgot that OpenMVS support is turned off for the statically compiled executables provided in this repository.
The reason is that I could never manage to link the OpenMVS libs statically to [mesh-tools](https://github.com/raphaelsulzer/mesh-tools).

I'm afraid you'll either need to export your point cloud with sensor positions to an `.npz` or `.ply` file which can be read by the `feat` tool, or you have to compile the `feat` tool yourself with OpenMVS support enabled.

**Comment by KevinCain** [comment]
Thanks again @raphaelsulzer, that makes sense.

Would another option be to use your [OMVS2NPZ](https://github.com/raphaelsulzer/mesh-tools/blob/main/CMakeLists.txt#L35) utility, then run the provided `feat` binary?

**Comment by raphaelsulzer** [comment]
Yes, exactly. You can also do that!
